services:
  reverse-proxy:
    image: traefik:latest
    hostname: reverse-proxy
    container_name: reverse-proxy
    restart: always
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - "traefik.http.middlewares.to-ssl-redirectscheme.redirectscheme.scheme=https"
      - "traefik.http.middlewares.to-ssl-redirectscheme.redirectscheme.permanent=true"
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.secureweb.address=:443
      - --certificatesresolvers.le.acme.email=volatileasm@protonmail.com
      - --certificatesresolvers.le.acme.storage=/certificates/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
      - --accesslog
      - --entryPoints.web.forwardedHeaders.insecure
      - --log
    ports:
      - 80:80
      - 443:443
    networks:
      - traefik-public
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-public-certificates:/certificates

  web:
    image: nginx:latest
    hostname: web
    container_name: web
#     build: .
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./public:/usr/share/nginx/html
      - ./public:/var/www/html
#       - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#       - ./nginx/nginxconfig/general.conf:/etc/nginx/general.conf
#       - ./nginx/nginxconfig/security.conf:/etc/nginx/security.conf
    restart: always
    networks:
      - traefik-public
    labels:
      - traefik.enable=true
      - traefik.http.routers.web-http.entrypoints=web
      - traefik.http.routers.web-http.rule=Host(`outline.naumov.company`)
      - traefik.docker.network=traefik-public
      - traefik.http.routers.web-https.entrypoints=secureweb
      - traefik.http.routers.web-https.rule=Host(`outline.naumov.company`)
      - traefik.http.routers.web-https.tls=true
      - traefik.http.routers.web-https.tls.certresolver=le
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
      - traefik.http.services.web.loadbalancer.server.port=80
      - traefik.http.routers.web-http.middlewares=https-redirect
    environment:
      - NGINX_PORT=80
      - NGINX_HOST=outline.naumov.company
    links:
      - php-fpm
      - outline_admin

  php-fpm:
    image: php:8-fpm
    hostname: php-fpm
    container_name: php-fpm
    networks:
      - traefik-public

  outline_admin:
    # build:
    #     context: ./docker/8.2
    #     dockerfile: Dockerfile
    image: slaweekq/outline_admin:latest
    hostname: outline_admin
    container_name: outline_admin
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${APP_PORT:-9696}:80"
      - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"
    volumes:
      - "./public:/var/www/html"
    environment:
      - PORT=9696
    networks:
      - traefik-public
    labels:
      - traefik.enable=true
      - traefik.http.routers.outline_admin-http.entrypoints=web
      - traefik.http.routers.outline_admin-http.rule=Host(`outline.naumov.company`)
      - traefik.docker.network=traefik-public
      - traefik.http.routers.outline_admin-https.entrypoints=secureweb
      - traefik.http.routers.outline_admin-https.rule=Host(`outline.naumov.company`)
      - traefik.http.routers.outline_admin-https.tls=true
      - traefik.http.routers.outline_admin-https.tls.certresolver=le
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
      - traefik.http.services.outline_admin.loadbalancer.server.port=80
      - traefik.http.routers.outline_admin-http.middlewares=https-redirect

volumes:
  traefik-public-certificates:

networks:
  traefik-public:
    driver: bridge
    external: true
