services:
  outline_admin:
    image: slaweekq/outline_admin:latest
    hostname: outline_admin
    container_name: outline_admin
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${APP_PORT:-9696}:80"
      - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"
    environment:
      - PORT=9696
    networks:
      - traefik-public
    labels:
      - traefik.enable=true
      - traefik.http.routers.outline_admin-http.entrypoints=web
      - traefik.http.routers.outline_admin-http.rule=Host(`localhost`)
      - traefik.docker.network=traefik-public
      - traefik.http.routers.outline_admin-https.entrypoints=secureweb
      - traefik.http.routers.outline_admin-https.rule=Host(`localhost`)
      - traefik.http.routers.outline_admin-https.tls=true
      - traefik.http.routers.outline_admin-https.tls.certresolver=le
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
      - traefik.http.services.outline_admin.loadbalancer.server.port=80
      - traefik.http.routers.outline_admin-http.middlewares=https-redirect

volumes:
  traefik-public-certificates:

networks:
  traefik-public:
    driver: bridge
