services:
  reverse-proxy:
    image: traefik:latest
    restart: always
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.secureweb.address=:443
      - --certificatesresolvers.le.acme.email=volatileasm@protonmail.com
      - --certificatesresolvers.le.acme.storage=/certificates/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
      - --accesslog
      - --entryPoints.web.forwardedHeaders.insecure
      - --log
    ports:
      - 80:80
      - 443:443
    networks:
      - traefik-public
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-public-certificates:/certificates

  outline_admin:
    image: slaweekq/outline_admin
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${APP_PORT:-9696}:80"
      - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"
    volumes:
      - ".:/var/www/html"
    networks:
      - traefik-public
    labels:
      - traefik.enable=true
      - traefik.http.routers.draitrin-http.entrypoints=web
      - traefik.http.routers.draitrin-http.rule=Host(`test.com`)
      - traefik.docker.network=traefik-public
      - traefik.http.routers.draitrin-https.entrypoints=secureweb
      - traefik.http.routers.draitrin-https.rule=Host(`test.com`)
      - traefik.http.routers.draitrin-https.tls=true
      - traefik.http.routers.draitrin-https.tls.certresolver=le
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
      - traefik.http.services.draitrin.loadbalancer.server.port=9696
    restart: unless-stopped

volumes:
  traefik-public-certificates:


networks:
  traefik-public:
    driver: bridge
    external: true
